name: Build and Deploy

on:
  push:
    # Publish sem ver tags das releases.
    tags: [ "v*.*.*" ]
    branches:
    - v1.0.0

env:
  TARGET: linux/arm64,linux/amd64
  BUILD_FLAGS: --no-cache

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        with:
          # Need tags for Makefile logic to work
          fetch-depth: 0
      - name: Build and Push Docker Images
        run: make push
